services:
  db:
    networks:
      default:
        aliases:
          - db
    image: postgres:14
    container_name: container_scrapescholardb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  init_db:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    container_name: init_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
    entrypoint: ["./wait-for.sh", "db", "/app/init_db.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      default:

  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    container_name: fastapi_container
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      SCIENCEDIRECT_APIKEY: ${SCIENCEDIRECT_APIKEY}
      SCOPUS_APIKEY: ${SCOPUS_APIKEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SERVER: db
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      default:

volumes:
  db_data: