services:
  
  nextjs:
    # image: node:20 
    build:
      context: ../../client/scrapescholar_client  # Context for Dockerfile
      dockerfile: ../../nextjs/Dockerfile  # Use your existing Dockerfile
    working_dir: /app
    volumes:
      - ../../client/scrapescholar_client:/app

    #only need if you want to expose port 3000 and bypass nginx proxy
    #ports:
      #- "3000:3000"
  
    command: "npm run build && npm run start"  #  "npm start" for production
    environment:
      - NODE_ENV=development  # "production" for production builds
  
  



  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./start_nginx.sh:/docker-entrypoint.d/start_nginx.sh
    ports:
      - "80:80"
      # - "443:443"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - nextjs
      #need to chmod +x start_nginx.sh
    entrypoint: ["/docker-entrypoint.d/start_nginx.sh"] 
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
