name: Run Python Unit Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SCIENCEDIRECT_APIKEY: ${{secrets.SCIENCEDIRECT_APIKEY}}
      SCOPUS_APIKEY: ${{secrets.SCOPUS_APIKEY}}
      DATABASE_URL: postgresql://student:student@localhost:5432/scrapescholartestdb
      PYTHONPATH: ./backend
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: scrapescholartestdb
      POSTGRES_SERVER: localhost
      POSTGRES_PORT: "5432"
      SECRET_KEY: "SECRET*#1234"
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        pip install -r requirements.txt
        
    - name: Run Python Unit Tests
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        pytest ./tests/unit
