name: Run Python Unit Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SCIENCEDIRECT_APIKEY: ${{secrets.SCIENCEDIRECT_APIKEY}}
      SCOPUS_APIKEY: ${{secrets.SCOPUS_APIKEY}}
      PYTHONPATH: ./backend
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_SERVER: ${{secrets.POSTGRES_SERVER}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U student" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U ${{secrets.POSTGRES_USER}}; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run init_db script  
        run: python backend/app/init_db.py

      - name: Run unit tests
        working-directory: ./backend
        run: pytest ./tests/unit --disable-warnings -v -s
