name: Build and Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          echo "SCIENCEDIRECT_APIKEY=${{secrets.SCIENCEDIRECT_APIKEY}}" >> docker/.env
          echo "SCOPUS_APIKEY=${{secrets.SCOPUS_APIKEY}}" >> docker/.env
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> docker/.env
          echo "PYTHONPATH=./backend" >> docker/.env
          echo "POSTGRES_USER=${{secrets.POSTGRES_USER}}" >> docker/.env
          echo "POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}" >> docker/.env
          echo "POSTGRES_DB=${{secrets.POSTGRES_DB}}" >> docker/.env
          echo "POSTGRES_SERVER=${{secrets.POSTGRES_SERVER}}" >> docker/.env
          echo "POSTGRES_PORT=${{secrets.POSTGRES_PORT}}" >> docker/.env
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> docker/.env
          echo "ENCRYPTION_KEY=${{secrets.ENCRYPTION_KEY}}" >> docker/.env
          echo "HOST_IP=${{secrets.HOST_IP}}" >> docker/.env
          echo "TEST_USER=${{ secrets.TEST_USER}}" >> docker/.env
          echo "TEST_PASSWORD=${{secrets.TEST_PASSWORD}}" >> docker/.env


      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        shell: bash

      - name: Build and Test with Docker Compose
        run: |
          docker-compose -f docker/docker-compose-postgres.yml --env-file docker/.env up -d --build


      - name: Verify Database and Table Setup
        run: |
          # Wait until PostgreSQL is ready
          until docker exec container_scrapescholardb pg_isready -U $POSTGRES_USER; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done
          # Check for tables in the database
          docker exec container_scrapescholardb psql -U $POSTGRES_USER -d $POSTGRES_DB -c "\dt"
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        shell: bash          

      - name: Stop and remove containers
        run: docker-compose -f docker/docker-compose-postgres.yml down