name: Build and Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          cd docker/
          echo "POSTGRES_USER=${{secrets.POSTGRES_USER}}" >> .env
          echo "POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}" >> .env
          echo "POSTGRES_DB=${{secrets.POSTGRES_DB}}" >> .env
          echo "POSTGRES_SERVER=db" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "DATABASE_URL=postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@db:5432/${{secrets.POSTGRES_DB}}" >> .env
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> .env
          echo "ENCRYPTION_KEY=${{secrets.ENCRYPTION_KEY}}" >> .env
          echo "SCIENCEDIRECT_APIKEY=${{secrets.SCIENCEDIRECT_APIKEY}}" >> .env
          echo "SCOPUS_APIKEY=${{secrets.SCOPUS_APIKEY}}" >> .env
          echo "TEST_USER=${{secrets.TEST_USER}}" >> .env
          echo "TEST_PASSWORD=${{secrets.TEST_PASSWORD}}" >> .env

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        shell: bash

      - name: Build and Test with Docker Compose
        run: |
          docker-compose -f docker/docker-compose-postgres.yml --env-file docker/.env up -d --build

      - name: Verify Database and Table Setup
        run: |
          # Wait until PostgreSQL is ready
          until docker exec container_scrapescholardb pg_isready -U $POSTGRES_USER; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done
          # Check for tables in the database
          docker exec container_scrapescholardb psql -U $POSTGRES_USER -d $POSTGRES_DB -c "\dt"
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        shell: bash          

      - name: Build FastAPI Backend
        run: |
          docker build -t fastapi-backend ./docker/fastapi

      - name: Start FastAPI Backend
        run: |
          docker-compose -f docker/docker-compose-postgres.yml --env-file docker/.env up -d fastapi

      - name: Wait for FastAPI Backend to Be Ready
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:8000/health_check; then
              echo "FastAPI is ready."
              exit 0
            fi
            echo "Waiting for FastAPI to be ready..."
            sleep 5
          done
          echo "FastAPI did not become ready in time."
          exit 1

      - name: Test Backend Endpoint
        run: |
          curl -X GET http://localhost:8000/users/get/1 || echo "Received expected error (e.g., 403)"

      - name: Stop and Remove Containers
        run: docker-compose -f docker/docker-compose-postgres.yml down