name: Run Coverage Reports

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      PYTHONPATH: ./backend
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_SERVER: ${{secrets.POSTGRES_SERVER}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
      # used in fastapi, academic API Keys
      SCIENCEDIRECT_APIKEY: ${{secrets.SCIENCEDIRECT_APIKEY}}
      SCOPUS_APIKEY: ${{secrets.SCOPUS_APIKEY}}
      NEXT_PUBLIC_ADMIN_USER: ${{ secrets.NEXT_PUBLIC_ADMIN_USER }}
      NEXT_PUBLIC_ADMIN_PASS: ${{ secrets.NEXT_PUBLIC_ADMIN_PASS }}
      #used in AR-3 tests
      DOMAIN: scrapescholar.me
      TEST_USER: ${{ secrets.TEST_USER}}
      TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
    services:
      postgres:
        image: postgres:latest
        env:
          PYTHONPATH: ./backend
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_SERVER: ${{secrets.POSTGRES_SERVER}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}       
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U student" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h ${{secrets.POSTGRES_SERVER}} -p 5432 -U student; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done

    - name: Run init_db script  
      run: python backend/app/init_db.py

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver

    - name: Run FastAPI Server
      working-directory: ./backend
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 & sleep 5
        curl -X GET http://0.0.0.0:8000/health_check

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      working-directory: ./client/scrapescholar_client
      run: npm install

    - name: Run Frontend NPM dev
      working-directory: ./client/scrapescholar_client
      run: | 
        npm run dev & sleep 10

    - name: Run Backend Coverage Report
      working-directory: ./backend
      env:
        DISPLAY: :99  
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        coverage run -m pytest tests --verbose && coverage report -m

    - name: Run Frontend Coverage Report
      working-directory: ./client/scrapescholar_client
      run: npm run test:unit -- --coverage        