name: Init DB Workflow

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'backend/app/**/*.py'
      - '.github/workflows/db_workflow.yml'
  push:
    branches:
      - '*'
    paths:
      - 'backend/app/**/*.py'
      - '.github/workflows/db_workflow.yml'

jobs:
  init-db:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./backend
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_SERVER: ${{secrets.POSTGRES_SERVER}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
    services:
      postgres:
        image: postgres:latest
        env:
          PYTHONPATH: ./backend
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_SERVER: ${{secrets.POSTGRES_SERVER}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}       
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U student" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U student; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run init_db script  
        run: python backend/app/init_db.py

      - name: Run tests
        run: pytest backend/tests/database --disable-warnings -v -s