name: Run Next.js Unit Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_ADMIN_USER: ${{ secrets.NEXT_PUBLIC_ADMIN_USER }}
      NEXT_PUBLIC_ADMIN_PASS: ${{ secrets.NEXT_PUBLIC_ADMIN_PASS }}
      NEXT_PUBLIC_ADMIN_PASS: ${{ secrets.NEXT_PUBLIC_HOST_IP}}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm install

    - name: Run Unit Tests
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm run test:unit   


