name: Run Integration Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        pip install -r requirements.txt




    - name: Serve next.js app
      working-directory: ./client/scrapescholar_client
      run: |
        npm run start &
        sleep 10
        curl -X GET http://localhost:3000/
        curl -X GET http://localhost:8000/health_check
        curl -X GET http://localhost:8000/sciencedirect?query=test  
        
    - name: Run Python Integration Tests
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        pytest ./tests/integration
    
        
    - name: Run FastAPI Server
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 & sleep 5
        curl -X GET http://localhost:8000/health_check


    - name: Run npm install
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm install

    - name: Run Next.js Integration Tests
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm run test:integration   



    - name: Run Build
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm run build

    - name: Serve next.js app
      working-directory: ./client/scrapescholar_client
      run: |
        npm run start &
        sleep 10
        curl -X GET http://localhost:3000/
        curl -X GET http://localhost:8000/health_check
        curl -X GET http://localhost:8000/sciencedirect?query=test 

