name: Run Integration Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SCIENCEDIRECT_APIKEY: ${{secrets.SCIENCEDIRECT_APIKEY}}
      SCOPUS_APIKEY: ${{secrets.SCOPUS_APIKEY}}
      DOMAIN: scrapescholar.me
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        pip install -r requirements.txt
        
    - name: Run Python Integration Tests
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        pytest ./tests/integration

    - name: Run FastAPI Server
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 & sleep 5
        curl -X GET http://0.0.0.0:8000/health_check

    - name: Run npm install
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm install

    - name: Run Build && unit and integration tests
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: | 
        npm run build

    - name: run Integration tests Next.js 
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm run test:integration
    
    - name: test ssl
      run: |
        curl https://$DOMAIN

    - name: test http redirection to https
      run: |

        # Perform an HTTP request and follow redirects
        REDIRECTS=$(curl -I -L -s -w "%{http_code} %{url_effective}\n" http://$DOMAIN)

        # Extract HTTP status code and final URL from last line of output
        STATUS_CODE=$(echo "$REDIRECTS" | tail -n 1 | awk '{print $1}')
        FINAL_URL=$(echo "$REDIRECTS" | tail -n 1 | awk '{print $2}')

        # Print status code and final redirected url for debugging purposes
        echo "Status Code: $STATUS_CODE"
        echo "Final URL: $FINAL_URL"

        # check if final url is https, and status code is 200, otherwise exit with 1 
        if [[ "$FINAL_URL" == https://*  &&  "$STATUS_CODE" -eq 200 ]]; then
            echo "Redirection from HTTP to HTTPS is working correctly."
        else
            echo "Redirection does not go to HTTPS."
        exit 1
        fi








