name: Run Selenium Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      PYTHONPATH: ./backend
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_SERVER: ${{secrets.POSTGRES_SERVER}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
      # used in fastapi, academic API Keys
      SCIENCEDIRECT_APIKEY: ${{secrets.SCIENCEDIRECT_APIKEY}}
      SCOPUS_APIKEY: ${{secrets.SCOPUS_APIKEY}}
      NEXT_PUBLIC_ADMIN_USER: ${{ secrets.NEXT_PUBLIC_ADMIN_USER }}
      NEXT_PUBLIC_ADMIN_PASS: ${{ secrets.NEXT_PUBLIC_ADMIN_PASS }}

      TEST_USER: ${{secrets.TEST_USER}}
      TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
    services:
      postgres:
        image: postgres:latest
        env:
          PYTHONPATH: ./backend
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_SERVER: ${{secrets.POSTGRES_SERVER}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}       
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U student" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h ${{secrets.POSTGRES_SERVER}} -p 5432 -U student; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done
    - name: Run init_db script  
      run: python backend/app/init_db.py

    - name: Run FastAPI Server
      working-directory: ./backend  # Adjust to the correct directory
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 & sleep 5
        curl -X GET http://0.0.0.0:8000/health_check


    - name: Run npm install
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm install

    - name: Run Build && unit tests
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: | 
        npm run dev & sleep 10

   
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
       
    - name: Debug Environment Variables
      run: |
        echo "TEST_USER: $TEST_USER"
        echo "TEST_PASSWORD: $TEST_PASSWORD"

    - name: run selenium tests
      env:
        DISPLAY: :99  
      working-directory: ./selenium_tests
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        pip install -r requirements.txt
        pytest *

   





