name: Run Unit Tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm install

    - name: Run Unit Tests
      working-directory: ./client/scrapescholar_client  # Adjust to the correct directory
      run: npm test
